### ISSUE TITLE
First frame remains stuck + leftovers + how to resize?

### ISSUE THREAD

**Issue by alecstheone** [giniedp/spritespin#11]
Hello I really like this script but I have some problems with it. Firstly it works perfect on th deesktop on chrome browser. I only have problem when I display it on the mobile. I'm currently developping an app with phonegap (framework based on html, css and javascript) and I'm facing some problems when displaying the sprite:
1) The first frame doesn't clear and if I use a transparent spritesheet (.png) the first frame is displaying under the animation. (this thing doesn't happends on desktop)
2) The script doesn't seem to calculate well the frames because on mobile and also on desktop you can see some leftover parts on top and right of the animation 
3) How to scale the image? For example it should be always 30% of the width of the screen and its corresponding height? (or vice-versa)
I tried setting some css values but it seems they're working in desktop but not on the mobile device where it cuts the animation on right and down parts.
$(".win-animation").css({'top':'140px','position':'absolute', 'width':'100%', 'height':'50%'});

this is my code:
    $(".win-animation").spritespin({
    source  : "img/mmmm.png", // path to sprite sheet
    width   : 200,  // width in pixels of the window/frame
    height  : 163,  // height in pixels of the window/frame
    frames  : 14,   // total number of frames
    framesX : 5,     // number of frames in one row inside the spritesheet
    frameTime: 60,
    behavior: 'drag'
  });

This is a video I made showing my problems on desktop and on the phone:
https://www.youtube.com/watch?v=fORpKF9edQc&list=UUcGZQ1LZBPIeDTvnv1y6RnA

I have a pretty big spritesheet and I would like to use canvas as in spritespin script so it'll run fast also on mobile devices.

Any help is appreciated!

**Comment by giniedp** [comment]
I assume this to be solved.
