### ISSUE TITLE
Sprite Sheets doesnt work on iOS Chrome

### ISSUE THREAD

**Issue by ac-bristol** [giniedp/spritespin#13]
For some reason, on Chrome iOS (latest version of iOS tested), the sprite sheet spin version doesn't work. It just tends to show the first frame but not actually spin. On your site, the image doesnt load at all.

**Comment by markedup** [comment]
Also experiencing this problem.

Using a 6x6 24-bit PNG sprite sheet and the default `canvas` SpriteSpin renderer, nothing displays in iOS Chrome 40.0.2214.69 (although the frame for rendering is in place and at the correct dimensions). However, switching to `image` rendering in the SpriteSpin options will at least show the first frame of the sprite sheet.

But in both instances, there's no apparent interaction response. The image remains fixed on the first frame of the sprite sheet and doesn't change.

I've tried switching between latest jQuery v1 and v2, and neither seems to make any difference to this problem in iOS Chrome.

**Comment by giniedp** [comment]
would you be so kind and test it with the current version 3.3.2 There was an issue with the preload counter that is fixed now. I dont have access to an iOS device right now.

**Comment by giniedp** [comment]
i close this due to age
