### ISSUE TITLE
Default preloadCount in error

### ISSUE THREAD

**Issue by Timak304** [giniedp/spritespin#15]
Hello, I had a problem with IE8 again, only the first image is loaded.
Because in the `load()` function in the `for` line 151 to 157, the first image finish loading before pushing the next into `images`. So the completness test line 146: 
if (!completed && (count >= (targetCount || **images.length**)) && firstLoaded && (typeof opts.complete === 'function')) {
thinks that every images have be loaded (if `targetCount` is not set).

Here `images.length` should be replaced by `src.length` to make sure we have the real count of images:
if (!completed && (count >= (targetCount || **src.length**)) && firstLoaded && (typeof opts.complete === 'function')) {

Regards

**Comment by giniedp** [comment]
thank you for pointing that out. Should solve some other errors too. Its updated with version 3.3.2

**Comment by Timak304** [comment]
I have a similar problem when preloadCount is set to 1 (on IE8 only).
Because on:
`data.sourceIsSprite = data.images.length === 1;`
images only got the first one, it should be:
`data.sourceIsSprite = data.source.length === 1;`
