### ISSUE TITLE
Required Zepto modules

### ISSUE THREAD

**Issue by bartiosze** [giniedp/spritespin#18]
I can see that spritespin can depend on Zepto instead of jQuery. Do you have a list of required zepto modules? It looks like bower-installed zepto is not enough for spritespin to work. Adding zepto-data fixes the problem.

My project has no other jQuery dependency than spritespin and I'd like to have as lightweight solution as possible.

**Comment by giniedp** [comment]
SpriteSpin has a fallback to zepto, but unfortunately i have never tested it. zepto-data sounds reasonable since spritespin stores a data object in the DOM element.

**Comment by bartiosze** [comment]
Ok, I'll try to find minimal setup that works with SpriteSpin.

I'd be happy to provide documentation PR.

Thanks for SpriteSpin;-)
