### ISSUE TITLE
How to disable the drag behavior?

### ISSUE THREAD

**Issue by alecstheone** [giniedp/spritespin#20]
I removed te drag behavior but the animation is still draggable. How to disbale this effect??

**Comment by giniedp** [comment]
take a look at the animate option. Its true by default. Set it to false.

**Comment by edgren** [comment]
Hello. I've set the animate option from true to false but only the animation for the panorama was stopped. I can still use the drag effect. I want to disable the drag effect completely but keep the animation effect of the panorama! How can I do this?

**Comment by giniedp** [comment]
ok, animate option is only for autostart the animation after load.
what behavior do you want instead?
Here is the implementation of the drag behavior
https://github.com/giniedp/spritespin/blob/master/src/spritespin.beh-drag.js#L75
You can implement and register your own behavior and activate it with the 'behavior' options

**Comment by edgren** [comment]
I want to disable the drag behaviour completely! :P I don't want to drag the panorama at all.
