### ISSUE TITLE
Is there an event when the rotation stops at a particular frame in sprite spin?

### ISSUE THREAD

**Issue by nutank** [giniedp/spritespin#21]
Hi,

I am using sprite spin in react js for implementing 360 deg view. I dynamically load an svg at every breakpoint when next is clicked. Currently the svg gets loaded immediately after next is clicked. What I would want is to load the svg after the frame stops at an image.

@giniedp . is there is any event when the rotation ends, so I could load svg when it stops at a frame.

Thanks!

**Comment by giniedp** [comment]
you could use the onFrame event which is called on each frame change. Then you can get the current frame number and compare that to whatever makes sense for you. 

There is no stop animation event. If you really need a stop event you can always monkeypatch the stopAnimation function. Its here
https://github.com/giniedp/spritespin/blob/master/src/spritespin.js#L421

override that function after the spritespin script has been loaded
```
  SpriteSpin._originalStopAnimation = SpriteSpin.stopAnimation;
  SpriteSpin.stopAnimation = function(data){
    SpriteSpin._originalStopAnimation(data);
    data.target.trigger('onAnimationStop');
  };
```

i think that could work

**Comment by nutank** [comment]
Thanks @giniedp ! that worked like a charm :+1:
