### ISSUE TITLE
responsive and hires/retina screen optimizations

### ISSUE THREAD

**Issue by piffpaffpuff** [giniedp/spritespin#22]
the canvas element does not include any retina support at the moment neither is it easy to get the whole thing responsive.

**Comment by nhterry** [comment]
I was able to add retina support for canvas.

Line 569:
    if (data.canvas){
      var context = data.canvas[0].getContext('2d'),
          devicePixelRatio = window.devicePixelRatio || 1,
          backingStoreRatio = context.webkitBackingStorePixelRatio ||
                            context.mozBackingStorePixelRatio ||
                            context.msBackingStorePixelRatio ||
                            context.oBackingStorePixelRatio ||
                            context.backingStorePixelRatio || 1,
          ratio = devicePixelRatio / backingStoreRatio;
      data.canvas[0].width = w * ratio;
      data.canvas[0].height = h * ratio;
      context.scale(ratio,ratio);
      data.canvas.css(css).hide();
    }

via http://www.html5rocks.com/en/tutorials/canvas/hidpi/

**Comment by giniedp** [comment]
The development branch got an update with retina support. Thanks for pointing out.

**Comment by giniedp** [comment]
finally in master
