### ISSUE TITLE
Sprite spin images/canvas not loading on consecutive initialisation in react.

### ISSUE THREAD

**Issue by nutank** [giniedp/spritespin#23]
Hi @giniedp ,  

I am using sprite spin plugin in reactjs for 360 degree view of images. So the markup is basically split into various react components. 

So I have a parent component which calls another child component that loads sprite spin in its div with a set of images. When we move to another view via state change, i render a new parent component which internally calls another child component which initialises the sprite spin plugin with a new array of images. Although, the images get loaded in the network, the canvas is not getting generated and if I try to access the api or data object it is undefined.

Although i destroy spritespin before initialising the second time, it seems like the older instance is not getting destroyed.

Is there any reason why this could happen? I even destroy the spritespin before initialising it the second time in the second view but still it does not work.

However, If I directly reload the 2nd view, the spritespin plugin gets initialised properly and the canvas gets rendered with the images.

Can you please provide me some ideas around why this could happen or as to what I am missing out. It would really be of great help if you could provide me with some insight around this. 

Thanks.

**Comment by curly33** [comment]
Hi @nutank. I'm looking to implement this for a React project as well. Have you had any success with SpriteSpin in React? 

@giniedp - Do you have any plans to convert this for React projects? Thanks all!

**Comment by moleCuleFFF** [comment]
+1 this it's driving me bonkers

**Comment by giniedp** [comment]
i have added an example on how to implement a custom spritespin component in react
http://spritespin.ginie.eu/samples/#/integration-react

this is my first attempt pulling something off with React. Let me know if you can get around your issues with that implementation or if you think there is a better way to hook into React lifecycle.

**Comment by cTxplorer** [comment]
@giniedp I am trying to plug in the react-integration into my react project. But somehow I am not able to render the images. Any idea on solving below error?

```
$ is not defined
ReferenceError: $ is not defined
```

My project structure: Two files for each component. And, ParentComponent is called directly in app.js for rendering. I installed jquery using `yarn install jquery`

Thanks.

**Comment by giniedp** [comment]
that depends on your setup. If you use webpack to bundle your javascript then you need the ProvidePlugin and declare jquery there
https://webpack.js.org/plugins/provide-plugin/#usage-jquery
