### ISSUE TITLE
Touch scrolling over sprite not possible

### ISSUE THREAD

**Issue by SLemming** [giniedp/spritespin#27]
If I have a spritespin element (regardless if it's a img-sprite or a canvas) I cannot scroll on touch devices if I scroll over the element. All touch events just going into the spritespin. But that is not necessary, if the sprite is just horizontally moved. Can you please provide touchscrolling vertically and do not catch these events if not necessary?

**Comment by giniedp** [comment]
This has been improved in Version 4.0.11 https://github.com/giniedp/spritespin/commit/294e7790f04a46af2200444119003918457e62bc

On first interaction with SpriteSpin the scroll is not disabled (this is unchanged)
On double tap within 200ms the scroll is not disabled (this is unchanged)
Scroll is only disabled if there was an interaction with SpriteSpin in the past 1500ms (this has changed)

The values can be controlled with the option `touchScrollTimer `

The ideal solution would have been if we could disable the touch scroll for vertical movements. However the chrome browser does throw an error if we try to cancel the `touchmove` event during a scroll. We can only safely disable the scroll on `touchstart` event. But during `touchstart` we dont know the intended move direction.
