### ISSUE TITLE
Change source data after initialize

### ISSUE THREAD

**Issue by betmakh** [giniedp/spritespin#28]
Hello. I think it would be great if we can change particular frame source through SpriteSpin instance  without re-initialization.

My current solution:
```
SpriteSpin.extendApi({
    replaceSourceFrame: function(src, frame){
      frame = frame || this.data.frame;
      this.data.source[frame] = src;
      SpriteSpin.create(this.data);
    }
});
```

Maybe You can offer more elegant solution for this?
Thank you.

**Comment by giniedp** [comment]
you can use 
SpriteSpin.updateFrame(data, newFrameValue);

**Comment by betmakh** [comment]
But what if I want to change source url of the frame, not just select another frame from data.source array?

**Comment by giniedp** [comment]
sorry, my above answer was totally incorrect. It was about how to update a frame number but that is not what you want.

If you dont want to reinitialize the whole plugin you need to update the `data.source` as you already did but also the `data.images` array. This should do the trick.

`
SpriteSpin.extendApi({
    replaceSourceFrame: function(src, frame){
      frame = frame || this.data.frame;
      this.data.source[frame] = src;
      this.data.images[frame].src = src;
    }
});
`

**Comment by giniedp** [comment]
Please reopen if that did not answer your question
