### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by kennynaoh** [giniedp/spritespin#30]
Hello @giniedp ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But there is a question want to ask.
I think the main file are `release/spritespin.js` and `release/spritespin.min.js` on [github](https://github.com/giniedp/spritespin).
But I am not sure does there any dependency files need to be grab under `src/`?
Or any other files need to be grab.
Please help me confirm that.
Thanks!

https://github.com/cdnjs/cdnjs/issues/8721

**Comment by giniedp** [comment]
hi, thanks for the question. I was about to add spritespin to cdnjs but got stuck in my daily work and postponed my intend.
You are correct. The files in release directory are the only ones that needs to be hosted. They are generated from the files in src. The only external dependency is the jQuery framework.

**Comment by kennynaoh** [comment]
Thanks!
But there are different file format before the version `3.2.1`.
Do we also just grab these two files `spritespin.js` and `spritespin.min.js` under `dist/`?
Or we need to grab others under `dist/`?
Thanks!

**Comment by giniedp** [comment]
the dist folder was confusing for many people, so i decided to put the spritespin.js and the spritespin.min.js files into the release folder. Before that one had to grab these files from the dist folder, now its the release folder. But its always the spritespin.js and the spritespin.min.js. All other files are just usage examples.

**Comment by giniedp** [comment]
Thanks for putting it on cdnjs

**Comment by kennynaoh** [comment]
You are welcome
