### ISSUE TITLE
fullscreen aspect ratio

### ISSUE THREAD

**Issue by easyw** [giniedp/spritespin#31]
Hi,
I tried the 
http://spritespin.ginie.eu/examples.html#fullscreen.html
example, and I noticed that the image get stretched when activating full screen...
Is it possible to maintain aspect ratio of the image when going in full screen mode?
thank you
Maurice

**Comment by giniedp** [comment]
hi
have you tried the size mode?
http://spritespin.ginie.eu/examples.html#sizing.html

**Comment by easyw** [comment]
Hi,
using 
`sizeMode: 'fit'` 
the full-screen result is fine (with correct aspect ratio), 
but this option is in conflict with the other option I'm using
`responsive: true`
using both, `sizeMode` will override `responsive` option behavior...
is there a workaround to keep both?
thank you

**Comment by giniedp** [comment]
good point. There is no simple workaround. I think the fullscreen api should be able to accept a 'sizeMode' option and use 'fit' as default. You can see here how it already accepts the 'source' option and resets it on fullscreen exit.
https://github.com/giniedp/spritespin/blob/master/src/spritespin.api-fullscreen.js#L128
I could fix that tonight or if you happen to fix it, send me a pull request.

**Comment by easyw** [comment]
Hi,
I had a look but I haven't found a solution..
I would wait for your fix.
Thank you a lot
Maurice

**Comment by giniedp** [comment]
its fixed now. You dont need to change anything. It uses by default the sizeMode 'fit'. It will have black background if the image does not cover the whole screen. You can change that with CSS giving your container a custom background-color

**Comment by easyw** [comment]
Hi,
thanks a lot for the fast fix!
It works fine...
there is still a minor issue... if you rotate the mobile device when in fullscreen, the image doesn't get resized to the new orientation values...

**Comment by easyw** [comment]
Hi again,
I published a wordpress plugin with your spritespin engine!
https://wordpress.org/plugins/spin360/
thank you for your jQ plugin!
Maurice

**Comment by easyw** [comment]
Hi,
I'm investigating a bit more on Fullscreen options...
I noticed that when using a Chrome browser (in general WebKit browser) Fullscreen works only if responsive is set to false
here a sample page with the first animation without responsive attribute
and the second one with responsive attribute
https://easyw.github.io/spin360/test-full-screen.html
Tested with firefox both are fine, with Chrome (both in win, osx, android) the responsive animation will fails to show in full screen

**Comment by easyw** [comment]
a small improvement for FS compatibility on Chrome and Opera for desktop and mobile here
https://easyw.github.io/spin360/test-full-screen-new.html
referring to spritespin-test.js script
still to investigate for safari in osx, ios

**Comment by giniedp** [comment]
whats the problem on safari? I dont see issues with the last link.
Unfortunately i am short on time. I might have a deeper look next week.

**Comment by easyw** [comment]
Hi, you are right ... safari in osx is fine, in ios fullscreen is not allowed so it shoud be fine
What I miss now is just resizing on orientation change...
thanks for having a look
Maurice

**Comment by easyw** [comment]
Hi, did you get a chance to investigate in full screen resizing when orientation is changing?
Should I reinitialize the plugin when the change orientation is caught?

**Comment by giniedp** [comment]
not enough time yet to actually fix it.

**Comment by giniedp** [comment]
should be fixed in version 3.4.2
the api detects an orientation change and reboots the plugin with correct width and height
