### ISSUE TITLE
jQuery 3 compatibility

### ISSUE THREAD

**Issue by tobystokes** [giniedp/spritespin#32]
bind() and unbind() have been deprecated.
But a very quick replace with their substitutes on() & off() seems to work fine in my limited testing.

https://github.com/TheScienceMuseum/spritespin/commit/696117520c1961f9c16d3fab491edf73044e7815

(Welcome to PR if you don't mind losing compatibility pre $1.7)

**Comment by giniedp** [comment]
SpriteSpin is removing the jQuery dependency in the next version

- https://spritespin-beta.ginie.eu/
