### ISSUE TITLE
Png Error

### ISSUE THREAD

**Issue by castrojunin** [giniedp/spritespin#33]
This plugin not working with png images.

**Comment by giniedp** [comment]
it does. Please be more specific about your issue.

**Comment by castrojunin** [comment]
Desculpe @giniedp, o problema era o tamanho da imagem(3MB). Já resolvi e está funcionando como você disse.

:-)

**Comment by giniedp** [comment]
yes, image size is important. everything above 2 Megapixels will be scaled down by some browsers. Spritespin tries to detect that, but the detection might fail on some PNG images, that have transparency

**Comment by sebipopa** [comment]
@giniedp I ran into an issue with a transparent png, the size was all crazy. I've set detectSubsampling:false and everything worked out.

**Comment by giniedp** [comment]
yes, subsampling detection with transparent images is not reliable. It goes wrong when border pixels or the outline of the image is transparent. There is a comment about that in the source code

https://github.com/giniedp/spritespin/blob/ce5c8eabb71f76e9bab654860d58152e441dc953/release/spritespin.js#L252

if anyone knows about a more reliable mechanism your pull reuest is welcome :)

**Comment by sebipopa** [comment]
Yes, I saw the comment, that's how I knew to disable it. Maybe a more clear explanation in the sample code (http://spritespin.ginie.eu/howto.html - Options) would help people that are getting this behavior.

Thanks for your plugin!

**Comment by giniedp** [comment]
agree, that topic should get a section in the howto page
