### ISSUE TITLE
Switching color in 360 degree view

### ISSUE THREAD

**Issue by abdullah-zudioz** [giniedp/spritespin#38]
Hi,
Your code is excellent and its is very useful in our project but now I had a requirements from my client they need 360 view product with  color switching is there are possibility to switch another color image and that also will be 360 view.  
Thank you

**Comment by giniedp** [comment]
i think your client wants to show the same product with the same 360 rotation, but switch the color of the product. In the end this will be a unique set of images per color. So every time the color is switched, the spritespin plugin has to be reinitialised with a new set of images. 

Spritespin can not manipulate the images but only display them.
