### ISSUE TITLE
Bind to "wheel" instead of "mousewheel" events

### ISSUE THREAD

**Issue by bpatram** [giniedp/spritespin#44]
It seems by default you bind to the event `mousewheel`: https://github.com/giniedp/spritespin/blob/0153d2ea7c1103cb3338ad1de028e82c1f14ce83/src/core/constants.ts#L20

This is a non-standard event; according to [MDN](https://developer.mozilla.org/en-US/docs/Web/Events/mousewheel)
> This interface is non-standard and deprecated. It was used in non-Gecko browsers only. Instead use the standard wheel event.

Instead you should be binding to just `wheel` to ensure browser compatibility. 

I do not believe anything in the core library or core plugins uses this handler, so it shouldn't be a breaking change. For backwards compatibility we can bind to both `mousewheel` and `wheel`.

**Comment by giniedp** [comment]
Thanks for reporting, yes, i can add 'wheel' to the event list. The library and the core plugins do not use that event. If any of your plugins need to use the 'wheel' event, you can temporarily go around that by pushing that event to the list before any initialisation.

```
SpriteSpin. eventNames.push('wheel')
```

**Comment by giniedp** [comment]
`wheel` event is now part of spritespin since version 4.0.5
