### ISSUE TITLE
Option "preloadCount" does not work as expected

### ISSUE THREAD

**Issue by hgeorgilas** [giniedp/spritespin#45]
Option  `preloadCount ` does not work as expected. Spritespin returns the whole set of images instead of preloading a subset and then call each individual frame on a `draw` event, which I imagine must be the use of this option.
My initialization:

```
     $('.spritespin').spritespin({
                source: SpriteSpin.sourceArray("path/{frame}.png", {
                    frame: [0, 120],
                    digits: -1,
                }),
                width: 400,
                height: 400,
                sense: -1,
                sizeMode: "fit",
                preloadCount: 10,
                plugins: [
                    'zoom',
                    '360',
                    'drag'
                ]
            });
```

**Comment by giniedp** [comment]
spritespin simply ensures that the first frame is loaded. If then the number of loaded frames exceeds the `preloadCount` it steps out of the preload step and goes into its lifecycle. Frames that have not been loaded wont be rendered, but still the draw event will be fired.

**Comment by hgeorgilas** [comment]
Thank you for the fast response. What I am trying to achieve is to load the content of the `sourceArray ` in a "lazy" way, so I can ensure that not all images requests are fired at the same time. It's a big load for both the client and the server, especially for large image files.Is there a way to handle such a situation from the options available for the plugin, and if not do you have a recommended way of doing that?
Thank you in advance.

**Comment by giniedp** [comment]
actually that is the job of the browser. The browser has a limit of parallel requests it will handle. Even if you schedule 120 image requests, not all of them are actually sent out by the browser. Instead they are queued and sent as soon as another request  has returned.

If you want to optimise load time, i would rather suggest to use spritesheets, instead managing the image requests

**Comment by hgeorgilas** [comment]
Thank you for the response, unfortunately spite sheets are not currently an option.
I will use a static image and initialize my spritespin object on hover, but an async option would be nice.
Thank your for your fantastic work and support on this plugin, really appreciate it :)

**Comment by giniedp** [comment]
You may be interested in the following example
http://spritespin.ginie.eu/samples/#/misc-lazy-load

This utilizes the IntersectionObserver and boots a spritespin instance only when it gets scrolled into the view.
you can find more info here https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/

I would leave that feature outside of spritespin for now
