### ISSUE TITLE
Canvas ist empty at only one image

### ISSUE THREAD

**Issue by zonky2** [giniedp/spritespin#48]
if wie have only one image at source, the canvas is empty...

I fill the source by PHP and sometimes only one image is displayed.

**Comment by giniedp** [comment]
please fill in more information. A jsfiddle example would be great, or at least your setup code.

**Comment by zonky2** [comment]
my Setup:

```
    <div id="mmSpriteSpin"></div>
    <script type='text/javascript'>
        $("#mmSpriteSpin").spritespin({
            // path to the source images.
            source : ["assets\/images\/5\/my_image_360_001-6bac8ea8.jpg"],
            width  : 400,   // width in pixels of the window/frame
            height : 400,   // height in pixels of the window/frame
            loop   : false, // If true loops the animation
            sense  : -1     // Interaction sensitivity used by behavior implementations
        });
    </script>
```

**Comment by giniedp** [comment]
i can't reproduce the problem that you describe
https://jsfiddle.net/giniedp/n35L3nxf/
your code looks fine for spritespin. However

1. you don't have to escape the slash in the file name
2. you probably might want to add a leading "/" to make it an absolute file path.

**Comment by zonky2** [comment]
hmmm...?
