### ISSUE TITLE
spritespin is incompatible with fancybox 3.x.x

### ISSUE THREAD

**Issue by AleshchenkoMaksim** [giniedp/spritespin#53]
When i use fancybox on site and try init spritespin then i have this error in console: 
`TypeError: self.instance.$refs is undefined`

See: https://jsfiddle.net/xpvt214o/337509/

**Comment by giniedp** [comment]
thx. just fixed it with version 4.0.6. There was an event collision and spritespin did fire the events without a namespace

**Comment by AleshchenkoMaksim** [comment]
when you can make the release 4.0.6. I really need, since I can not push feature to prod.

**Comment by AleshchenkoMaksim** [comment]
Oh, I already saw release on npmjs.com. Thanks
