### ISSUE TITLE
is it possible to load the first frame image then start to load the others

### ISSUE THREAD

**Issue by edisonchen1985** [giniedp/spritespin#55]
I have encountered an issue that if the image frames are of bigger size (let's say 200KB per image), and if there are 30 images to load inside the spritespin source, it will really take some time to finally see the images appear on the webpage. So I am wondering is it possible the webpage will load the first frame image, so we can see the image appears then it load all the remaining. (like the browser finishes rendering the first image with the DOM, then start to load the other images to append into the DOM). 

Thanks

**Comment by giniedp** [comment]
You can use the callbacks `onInit` and `onLoad` and then put the first frame as css background-image

```js
      $('.spritespin').spritespin({
        // ... your options
        onInit: function(e, data) {
          data.target.css({ "background-image": `url(${data.source[0]})` })
        },
        onLoad: function(e, data) {
          data.target.css({ "background-image": null })
        }
      });
```

You can also wrap that up in a custom module

```js
      SpriteSpin.registerPlugin('preloader', {
        onInit: function(e, data) {
          data.target.css({ "background-image": `url(${data.source[0]})` })
        },
        onLoad: function(e, data) {
          data.target.css({ "background-image": null })
        }
      })
```

And then use that in your config

```js
      $('.spritespin').spritespin({
        // ... your options
        plugins: ['preloader', '360', 'drag'],
      });
```

**Comment by buzzguy** [comment]
@giniedp Is there a way to do this with a sprite sheet (once it loads the first frame of the jpg)?

**Comment by giniedp** [comment]
No, not with a sprite sheet. A sprite sheet is a single image that contains multiple frames. One can only load a whole image, not a subsection of that. What you need is a preview image that contains a single frame and use that as background
