### ISSUE TITLE
playto mentioned frame number  & lane number in3DView

### ISSUE THREAD

**Issue by Jogii** [giniedp/spritespin#58]
I observed that the playto function animates to the instance of corresponding frame number, i am using spritespin 3D View and want to playto a corresponding frame and lane number combination, how to achieve the same?

**Comment by Strae** [comment]
Have you find a solution?
Im also looking for something like nextLane() o prevLane()

**Comment by Jogii** [comment]
i used the "onFrameChanged" event extending spritespin spinapi, onframeChanged event providesyou the data which contains the data.frame and data.lane info.
