### ISSUE TITLE
playTo() not going by shortest path

### ISSUE THREAD

**Issue by datainvestor** [giniedp/spritespin#59]
Hey how can i make playTo() in the api go to the target frame by shortest path? I read that you can set the options to behave like that but i cant get it to work:
var array = [15, 60, 85, 108]
var currentImage = 0;

$('button.fwd').click(function(){
next()
//e.preventDefault();
$('.spritespin').spritespin('api').playTo(array[currentImage], nearest = true);
console.log(array[currentImage])
});

$('button.back').click(function(){
prev()
$('.spritespin').spritespin('api').playTo(array[currentImage], nearest= true);
console.log(array[currentImage])
});

**Comment by giniedp** [comment]
you are not passing the `nearest` option.

instead of this
```
$('.spritespin').spritespin('api').playTo(array[currentImage], nearest = true);
```

do this
```
$('.spritespin').spritespin('api').playTo(array[currentImage], { nearest: true });
```

Here is an example
https://jsfiddle.net/giniedp/md3kg605/12/
