### ISSUE TITLE
Spritespin not show when put into bootstrap modal

### ISSUE THREAD

**Issue by boychanhboy** [giniedp/spritespin#61]
I wrap Spritespin in boostrap modal, first time click open modal, everything work fine but, if i close modal and reopen several times, my spritespin not show up.

**Comment by boychanhboy** [comment]
`$('.modal360').click(function(e){
			e.preventDefault();
			var href = jQuery(this).attr('href');
			$(href).modal('toggle');
			$('.spritespin').spritespin({
				source: SpriteSpin.sourceArray('//bizweb.dktcdn.net/100/340/549/products/san-pham-forester-360-{frame}.jpg?v=1545194339830', {
					frame: [1, 24], 
					digits: 1 
				}),
				frameTime: 60, 
				sense: -1,
				responsive: true
			});
});`

**Comment by boychanhboy** [comment]
https://zima.vn/tui-nho-nhan-mat-quy

**Comment by giniedp** [comment]
I dont see any problem. The modal opens and spritespin loads (with a little delay) any time i toggle the 360 button

**Comment by boychanhboy** [comment]
Lol, i dont know why 😢 so I do this

`$('.modal360').click(function(e){
			e.preventDefault();
			var href = jQuery(this).attr('href');
			jQuery(href).modal('toggle');


			$('.spritespin').spritespin({
				source: SpriteSpin.sourceArray(''+newUrl+'products/san-pham-'+productName+'-360-{frame}.jpg?'+variantImage+'', {
					frame: [1, totalFrame], // how much image
					digits: 1 // step increase
				}),
				frameTime: 60,//speed 
				sense: -1,
				responsive: true
			});

			setTimeout(function(){ 
				$('.spritespin').spritespin({
					animate: true
				})
			}, 500);
		});
		$('#modal360').on('hidden.bs.modal', function () {
			$(".spritespin").spritespin("destroy");
			console.log('destroy 360');

		})`
and it work like charm.
Anyway, thanks for reply your lib so awesome, i love it 👍
