### ISSUE TITLE
on zoom adapt canvas resolution

### ISSUE THREAD

**Issue by easyw** [giniedp/spritespin#64]
Hi,
I'm trying to introduce [panzoom](https://github.com/timmywil/panzoom) and a [modal lightbox](https://github.com/kylefox/jquery-modal) on [spritespin wordpress plugin](https://wordpress.org/plugins/spin360/).
Here a working sample page:
https://easyw.github.io/spritespin-zoom-lightbox/
what I have noticed is that if I use a small spritespin canvas, even when using high res images (1920x1080), the canvas is rendering at the canvas size.
If I apply a panzoom zoom, I would like to apply a new data instance to adapt the resolution to the new zoom (the same issue using the lightbox modal option).
Using full screeen instead, the image get rendered at higher resolution and the zoom result is much nicer.
Would you please suggest a way, if possible, to improve this behavior?
Thanks in advance
Maurice

**Comment by giniedp** [comment]
On zoom the canvas display area is increased via CSS transform. But the Backbuffer of the canvas keeps unchanged. You have to re-render the canvas with a high resolution backbuffer. The way to go is to change the `canvasRatio` option of spritespin. I did it like this

```js
$("canvas").on("panzoomzoom", function(e, p) {
  $(".spritespin1").spritespin({ canvasRatio: p.scale * window.devicePixelRatio });
})
```

This seems to work (tested on screens with devicePixelRation of `1` and `2`). However this forces spritespin to reboot which means that it puts itself into preloading mode and introduces a short flicker.

I'd have to fix that or allow a caller to tell spritespin to update an option without a reboot but instead with a re-layout only.

**Comment by giniedp** [comment]
This is actually already possible but requires a few more lines of code. The following works without flicker.

```js
$("canvas").on("panzoomzoom", function(e, p) {
  var data = $(".spritespin1").spritespin("data");
  data.canvasRatio = p.scale * window.devicePixelRatio;
  SpriteSpin.applyLayout(data);
  SpriteSpin.updateFrame(data, data.frame);
  data.stage.show();
});
```

**Comment by easyw** [comment]
@giniedp 
thanks a lot!
This is exactly what I needed.
Great and very powerful jQuery plugin!
:smile_cat:
