### ISSUE TITLE
data is undefined on API access

### ISSUE THREAD

**Issue by Cruiser13** [giniedp/spritespin#66]
The following line does cause an error "data is undefined" in browser.
`var data = $target.data(namespace);`
Steps to reproduce:
```
$("#mySpriteSpin").spritespin({ /* ... options ... */ })
var api = $("#mySpriteSpin").spritespin("api");
$('#prev').click(function(){
api.stopAnimation();
api.prevFrame();
});

$('#next').click(function(){
api.stopAnimation();
api.nextFrame();
});
```

**Comment by giniedp** [comment]
i can not reproduce it
https://stackblitz.com/edit/spritespin-example-api-usage?file=index.html

But i can think of 2 scenarios where `data` may be undefined.

1. if you try to access the api before spritespin has been initialized e.g.
```js
var api = $("#mySpriteSpin").spritespin("api");            // <-- will cause error

$("#mySpriteSpin").spritespin({ /* ... options ... */ })
```
2. if you try to access the api after the original DOM object has been destroyed or recreated e.g.
```js
$("#mySpriteSpin").spritespin({ /* ... options ... */ })

// ... some code that will destroy "#mySpriteSpin"

var api = $("#mySpriteSpin").spritespin("api");
```

**Comment by Cruiser13** [comment]
Thank you for your reply. I didn't use the $(document).ready(function() {
If I wrap my function into it like you did this works nicely. Thanks!
