### ISSUE TITLE
IE 11 - Slider don't work

### ISSUE THREAD

**Issue by Messa1** [giniedp/spritespin#71]
I test you script on various browser.
Slider don't work an IE and Edge, i test you demo also.

http://spritespin.ginie.eu/samples/#/misc-slider

**Check here my screencast**
https://drive.google.com/file/d/1QWeBTXxP35QdxKjQFV0HvHZVa1NeoNg2/view

**Also tried in a jsfiddle**
https://jsfiddle.net/4cvzh7t6/

**Comment by Messa1** [comment]
@giniedp did you check the problem?

**Comment by giniedp** [comment]
i do not have access to IE11. My guess is that IE11 does not trigger an `input` event which is confirmed by https://www.impressivewebs.com/onchange-vs-oninput-for-range-sliders/ 
IE11 would however work with this change
```diff
-       .on("input", function(e) {
+       .on("change", function(e) {
          SpriteSpin.updateFrame(data, e.target.value);
        })
```
But other browsers will not trigger that event until the slider is released.

My advise ist to use another slider solution, the examples are only for demonstration purposes of how to interact with the API. They are not necessarily cross browser solutions.

**Comment by Messa1** [comment]
Thanks for your feedback. Maybe i will customize it a bit and check if IE or Edge is in use.
