### ISSUE TITLE
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. at (spritespin.min.js:1)

### ISSUE THREAD

**Issue by pratika2395** [giniedp/spritespin#72]
I'm trying to create a 360 degree image spin using spritespin. But i'm getting this error at the begining of spritespin library

  $('.spritespin').spritespin({     //in console, error points this line
                    source: "{{asset($reel_pic)}}",
                    width: 1000,
                    height: 1000,
                    frames: 30,
                    framesX: 5,                    
                    sense: 1,
                    loop:false,
                    frame:0,
                    frameTime: 90,
                    onLoad: function () {
                        $('#reel00').remove();
                    },
                    scrollThreshold   : 100,
                    responsive:true
                });

**Comment by giniedp** [comment]
can not do anything without a reproducable scenario.

**Comment by pratika2395** [comment]
@giniedp ,i understand. shall i share the code part of spritespin?

**Comment by giniedp** [comment]
you can use https://stackblitz.com/ or similar service to setup a scenario that i can then verify. Sharing code or anything that gives me more insight into your setup could help to spot the issue.

Do you use any other plugins? What is your html structure? What else is happening outside of spritespin?

**Comment by pratika2395** [comment]
@giniedp , sorry, i have fixed the issue. The error was in the way i called the spritespin class in div. Thanks for ur response. 
BTW, i have another doubt. We have an requirement like we have many images(colored). We need to show the images based on color chosen by the user. For one particular image (say orange), we need to show 360 degree image rotation. 

I have done using ajax call, when the user selects color, corresponding images are shown. spritespin works well on the first time. But when the user clicks the orange for 2nd time, the 360 degree rotation is not working.

we need to show rotation whenever user clicks orange. Is there any way to do this? or this is due to any bug in my code? If u want to view my code, i can share u.

**Comment by pratika2395** [comment]
@giniedp , i found a solution for my above question. i need to use animate property. thanks, there is  no error in the plugin side.
