### ISSUE TITLE
Loop False is not working

### ISSUE THREAD

**Issue by orbitpixel** [giniedp/spritespin#73]
`$("#playblast-seq").spritespin({
            source: frames,
            width: $width,
            height: $height,
            plugins: [
            '360',
            'drag'
            ],
            reverse: false,
            module: "360",
            sense: -1,
            animate: false,
            **loop: false**,
            frames: frames.length,
            stoppFrame: frames.length,
            frameWrap: false,
            frameTime: 30,
            enableCanvas: false,
            onFrameChanged: () => {
                api.s27();
            },`

Loop false is not working.
I have 27 images frame by frame

**Comment by giniedp** [comment]
i can not replicate an issue with the `loop: false` setting. Please provide a reproducable example.
What exactly is the behavior that you expect from your settings? What version do you use?

These are your settings
```js
{
  source: frames,
  width: $width,
  height: $height,
  plugins: [ '360', 'drag' ],
  reverse: false,
  module: "360", // dont use this, if you already provide a plugins array
  sense: -1,
  animate: false, // The animation wont even start automatically
  **loop: false**, // I assume the ** is just for formatting?
  frames: frames.length,
  stoppFrame: frames.length, // Here is a typo. it should be ''stopFrame". But you actually dont need it, if you are using frames.length
  frameWrap: false, // this is not an option in current spritespin version. You mean 'wrap'  ?
  frameTime: 30,
  enableCanvas: false, // this is not an option in current spritespin version
  onFrameChanged: () => {
    api.s27(); // What does that do?
  }
```
