### ISSUE TITLE
Is there a way to use this plugin in react without jquery 

### ISSUE THREAD

**Issue by oblivionbees** [giniedp/spritespin#76]
Thanks for the awesome plugin 👍🏼 

from the example https://webpack.js.org/plugins/provide-plugin/#usage-jquery
i see Jquery is a must for using this plugin. we don't want to use Jquery in our application, is there a way to use this plugin in react without using Jquery 

@giniedp any help is much appreciated.

**Comment by giniedp** [comment]
i totally understand that but unfortunately not, at least not yet. I have a local branch where i am about to remove the jQuery dependency wich i could push today. But i doubt that it will be released any time soon.

**Comment by giniedp** [comment]
@oblivionbees hey, i am happy to tell that a beta version of spritespin is available. no jQuery dependency any more.

- install as `spritespin@beta`
- https://spritespin-beta.ginie.eu/

The API should not change at this stage. I am working on examples and documentation and watching for bug reports.
