### ISSUE TITLE
Any way to make it spin just once

### ISSUE THREAD

**Issue by BenComicGraphics** [giniedp/spritespin#80]
I need spritespin to spin just once.

**Comment by giniedp** [comment]
set the option `loop` to false

```js
spritespin({
  // ...
  animate: true,
  loop: false
})
```

**Comment by BenComicGraphics** [comment]
> set the option `loop` to false
> 
> ```js
> spritespin({
>   // ...
>   animate: true,
>   loop: false
> })
> ```

My fault.  Th issue is I need to use a trigger or button to Trigger a single 360 rotation.  And if possible do it 50% faster than normal.  I'm using the vue events as well.
