### ISSUE TITLE
Mouse movement plugin not working

### ISSUE THREAD

**Issue by newoldschool** [giniedp/spritespin#88]
Hello, sorry I'm not an expert programmer, there is any more detailed tutorial about how to use the mouse movement plugin?
I tried to copy/paste the code offered in your "Examples" but it's not working.

I tried to google this information, I tried to find tutorials on YouTube but nothing.
Probably is something very simple but I just don't know what to do it.

I just want a helmet in the center of my website  that will turn 180ª, like a head saying "no". 
But I want that movement to follow the mouse cursor, if the mouse is on the left side of the screen the animation should turn the helmet to the left.

I hope you can help me, thanks!

**Comment by giniedp** [comment]
here is a working example on stackblitz
https://stackblitz.com/edit/spritespin-example-y9guco?devToolsHeight=33&file=index.html

**Comment by newoldschool** [comment]
Okay now is working with that example, maybe I messed up because sometimes classes are used, and sometimes IDs are used, as I said I'm not a pro soy maybe that easy detail messed up my code.

You can close this, and hopefully this can help other beginners like me in the future, thanks!
